### ISSUE TITLE
SVG and DNA export darken image!

### ISSUE THREAD

**Issue by JoHNplusb** [tux3/Evolve#32]
If you export the DNA and then reimport it, the image is darker than before, as if some polygons had different brightness or alpha, the fitness value is also lower than before. If you then start the process, many areas of the image will be reconstructed respectively.

Another example to show this:
If you export a PNG and an SVG, then export and reimport the DNA, and then export a second png and a second SVG, you will notice that the two PNGs look different. The second one is darker, as mentioned before. The SVGs, however, looks exactly the same and both show the darker version that the second PNG shows.

This is really a pity because the program is generelly really nice, but its most interesting features, the SVG and DNA export both seem to have this bug.

**Comment by tux3** [comment]
This is now fixed.
