### ISSUE TITLE
Qt 5.1.1 compile error

### ISSUE THREAD

**Issue by godspeed1989** [tux3/Evolve#33]
At https://github.com/tux3/Evolve/blob/master/mutation.cpp#L41

`QVector::takeAt()` function was introduced in Qt 5.2.
```
Poly poly = newPolys.takeAt(source);
```
Equivalent to
```
Poly poly = newPolys.at(source);
newPolys.remove(source);
```

**Comment by tux3** [comment]
Yes, you'll need at least Qt 5.2, it's intended :)

Wontfix because I don't want to be limited to 5.1 if I pick it up again.
