### ISSUE TITLE
Image stops evolving after 15000 polys

### ISSUE THREAD

**Issue by Xaue** [tux3/Evolve#36]
After hitting 15000 polys the image will continue increasing in generation but will be no longer generate any polys.

**Comment by tux3** [comment]
If you  look in the settings, there's a minimum of 15000 and a maximum of 150000.
When the minimum is reached, it stops spamming new polys and tries to improve the existing ones, but the current algorithm isn't very effective.

So to keep getting the usual behavior, just raise the poly minimum in the settings.
